
#Api Idea Index
GET https://localhost:5001/ideas

#####################################
#Api Idea Create
POST https://localhost:5001/ideas
content-type: application/json

{
    "Content":"Buy Car255",
    "Confidence":4,
    "Ease":3,
    "Impact":2  
}

#####################################
#Api Idea Get By Id
GET https://localhost:5001/ideas/1

#####################################
#Api Idea Update
PUT https://localhost:5001/ideas/2
content-type: application/json

{
    "Content":"Buy Car Brand New",
    "Confidence":4,
    "Ease":3,
    "Impact":2,
    "Id":2  
}

#####################################
#Api Idea Delete
DELETE  https://localhost:5001/ideas/2


#####################################
#Api Users Create
POST https://localhost:5001/users
content-type: application/json

{
  "email": "kikolinsss@codementor.io",
  "name": "Jack Black",
  "password": "the-Secret-123"
}

#####################################
#Api Users Current
GET https://localhost:5001/me
content-type: application/json
X-Access-Token: 5AUbedW8b2PX4FIr0DM7BjoZQ4NjPYspMLNvhY/Ak7I=

