# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: idea_app_db
    ports:
      - 5434:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080